- name: Create OpenShift Pipelines OperatorGroup
  kubernetes.core.k8s:
    state: present
    namespace: openshift-operators
    definition: "{{ lookup('template', 'openshift-pipelines-operatorgroup.yaml.j2') }}"
  tags:
    - pipelines

- name: Create OpenShift Pipelines Subscription
  kubernetes.core.k8s:
    state: present
    namespace: openshift-operators
    definition: "{{ lookup('template', 'openshift-pipelines-subscription.yaml.j2') }}"
  tags:
    - pipelines

# CSV Ready待ち
- name: Wait for OpenShift Pipelines CSV
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: openshift-operators
  register: r_pipeline_csv
  retries: 60
  delay: 20
  until:
    - r_pipeline_csv.resources | length > 0
    - r_pipeline_csv.resources
      | selectattr('status.phase', 'defined')
      | selectattr('status.phase', 'equalto', 'Succeeded')
      | list | length > 0
  tags:
    - pipelines

# webhook deployment待ち
- name: Wait for tekton operator webhook deployment
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: openshift-operators
    name: tekton-operator-webhook
  register: r_tekton_webhook
  retries: 60
  delay: 10
  until:
    - r_tekton_webhook.resources | length > 0
    - r_tekton_webhook.resources[0].status.readyReplicas is defined
    - r_tekton_webhook.resources[0].status.readyReplicas | int > 0
  tags:
    - pipelines

# TektonConfig
- name: Create TektonConfig
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operator.tekton.dev/v1alpha1
      kind: TektonConfig
      metadata:
        name: config
      spec:
        profile: all
  tags:
    - pipelines

# pipelines controller待ち
- name: Wait until Pipelines Pods are ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: openshift-pipelines
    name: tekton-pipelines-controller
  register: r_pipeline_controller_deployment
  retries: 60
  delay: 15
  until:
    - r_pipeline_controller_deployment.resources | length | int > 0
    - r_pipeline_controller_deployment.resources[0].status.readyReplicas is defined
    - r_pipeline_controller_deployment.resources[0].status.readyReplicas | int > 0
  tags:
    - pipelines

- name: Wait until Tekton webhook is ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: openshift-pipelines
    name: tekton-pipelines-webhook
  register: r_pipeline_webhook
  retries: 60
  delay: 10
  until:
    - r_pipeline_webhook.resources | length > 0
    - r_pipeline_webhook.resources[0].status.readyReplicas is defined
    - r_pipeline_webhook.resources[0].status.readyReplicas | int > 0
  tags:
    - pipelines

- name: Download tkn CLI
  get_url:
    url: "{{ ocp4_installer_root_pipeline_url }}/pipeline/{{ pipelines_tkn_version }}/tkn-linux-amd64-{{ pipelines_tkn_version }}.tar.gz"
    dest: "/tmp/tkn-linux-amd64-{{ pipelines_tkn_version }}.tar.gz"
  tags:
    - pipelines

- name: Install OpenShift Pipelines CLI (tkn)
  become: true
  unarchive:
    src: "/tmp/tkn-linux-amd64-{{ pipelines_tkn_version }}.tar.gz"
    remote_src: true
    dest: /usr/local/bin
    mode: '0755'
    owner: root
    group: root
  args:
    creates: /usr/local/bin/tkn
  tags:
    - pipelines

- name: Setup tkn bash completion
  become: true
  shell: "/usr/local/bin/tkn completion bash >/etc/bash_completion.d/tkn"
  args:
    creates: /etc/bash_completion.d/tkn
  tags:
    - pipelines