apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: test
  labels:
    strimzi.io/cluster: cafe-cluster              # ← Kafka クラスタ名に合わせて
  namespace: quarkuscoffeeshop-demo                # ← Kafka クラスタがある namespace に変更
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - operations:
          - Read
          - Write
          - Describe
        resource:
          type: topic
          name: ""
          patternType: prefix
        host: '*'
      - operations:
          - Read
        resource:
          type: group
          name: ""
          patternType: prefix
        host: '*'