apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: quarkusdroneshop-rhdh
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: ${BASE_URL}

    backend:
      auth:
        externalAccess:
        - type: legacy
          options:
            secret: "${BACKEND_SECRET}"
            subject: legacy-default-config
      baseUrl: ${BASE_URL}
      cors:
        origin: ${BASE_URL}

    auth:
      environment: production
      token: ${AUTH_GITHUB_CLIENT_TOKEN}
      providers:
        github:
          production:
            clientId: ${AUTH_GITHUB_CLIENT_ID}
            clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

    integrations:
      github:
        - host: ${GITHUB_HOST_DOMAIN}
          apps:
            - appId: ${AUTH_GITHUB_APP_ID}
              clientId: ${AUTH_GITHUB_CLIENT_ID}
              clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
              webhookUrl: ${GITHUB_WEBHOOK_URL}
              webhookSecret: ${GITHUB_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_PRIVATE_KEY_FILE}

    signInPage: github

    catalog:
      ui:
        create:
          enabled: true
      providers:
        githubOrg:
          githubUrl: "https://${GITHUB_HOST_DOMAIN}"
          orgs:
            - "${GITHUB_ORGANIZATION}"
          token: "${GITHUB_TOKEN}"
          schedule:
            frequency: PT60S
            initialDelay: PT30S
            timeout: PT120S
      locations:
        - type: file
          target: /opt/app-root/src/catalog-info.yaml
          rules:
            - allow: [User, Group]
        - type: url
          target: "https://github.com/quarkusdroneshop/developerhub-skeleton/blob/main/reward/template.yaml"
          rules:
            - allow: [Template]
          schedule:
            frequency: PT60S
            initialDelay: PT30S
            timeout: PT120S

    featureFlags:
      scaffolder: true

    scaffolder:
      defaultAuthor:
        name: Noriaki Mushino
        email: nmushino@redhat.com
      github:
        visibility: public

    enabled:
      kubernetes: true
      argocd: true
      tekton: true

    kubernetes:
      clusterLocatorMethods:
        - type: config
          clusters:
            - authProvider: serviceAccount
              name: "${K8S_CLUSTER_NAME}"
              serviceAccountToken: "${K8S_CLUSTER_TOKEN}"
              url: "${K8S_CLUSTER_URL}"
              skipTLSVerify: true
      customResources:
        - apiVersion: v1
          group: route.openshift.io
          plural: routes
        - apiVersion: tekton.dev/v1beta1
          group: tekton.dev
          plural: pipelineruns
        - apiVersion: tekton.dev/v1beta1
          group: tekton.dev
          plural: pipelines
        - apiVersion: tekton.dev/v1beta1
          group: tekton.dev
          plural: taskruns
        - apiVersion: tekton.dev/v1beta1
          group: tekton.dev
          plural: tasks
      serviceLocatorMethod:
        type: singleTenant

    argocd:
      appLocatorMethods:
        - type: config
          instances:
            - name: main
              url: "${ARGOCD_INSTANCE_URL}"
              username: "${ARGOCD_USERNAME}"
              password: "${ARGOCD_PASSWORD}"

    proxy:
      '/argocd/api':
        target: "${ARGOCD_INSTANCE_URL}/api/v1/"
        changeOrigin: true
        secure: false
        headers:
          Cookie:
            $env: "${ARGOCD_AUTH_TOKEN}"

    permission:
      rbac:
        admin:
          users:
            - name: user:default:nmushino
        pluginsWithPermission:
          - catalog
          - scaffolder
          - permission
          - auth
          - techdocs
          - kubernetes
          - catalog-import
          - search
          - cost-insights
          - api-docs
          - lighthouse
          - catalog-graph
          - github-actions
          - tekton