apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sample-blog
  description: デモンストレーション用のサービスです
  labels:
    app: sample-blog
  links:
    - url: https://console-openshift-console.apps.cluster-8sffx.8sffx.sandbox2156.opentlc.com/k8s/cluster/projects/sample-blog
      title: OpenShift Console
      icon: dashboard
    - url: https://nginx-sample-blog.apps.cluster-8sffx.8sffx.sandbox2156.opentlc.com
      title: Application Web Site
      icon: dashboard
    - url: https://github.com/quarkusdroneshop/quarkusdroneshop-web.git
      title: App Repository
      icon: github
  annotations:
    backstage.io/kubernetes-label-selector: 'app=quarkusdroneshop-web'
    backstage.io/kubernetes-namespace: quarkusdroneshop-web
spec:
  type: website
  owner: user:default/nmushino
  lifecycle: production