apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-info
  namespace: quarkusdroneshop-rhdh
data:
  catalog-info.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: nmushino
      annotations:
        keycloak.org/id: 58e6ed84-3563-4def-9537-cbe22a040f79
        backstage.io/email: nmushino@redhat.com
    spec:
      profile:
        displayName: Noriaki Mushino
        email: nmushino@redhat.com
      memberOf:
        - admins
    ---
    ---
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: user1
    spec:
      profile:
        displayName: User 1
      memberOf:
        - admins
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: admins
    spec:
      type: team
      profile:
        displayName: Administrators
        email: nmushino@redhat.com
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: a-cluster
      description: DroneShopのフロントクラスタ
    spec:
      owner: team-a
    ---
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: b-cluster
      description: DroneShopのフロントサービスクラスタ
    spec:
      owner: team-b
    ---
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: c-cluster
      description: DroneShopのバックヤードクラスタ
    spec:
      owner: team-c
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: team-a
    spec:
      type: team
      profile:
        displayName: Team A
        email: team-a@example.com
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: team-b
    spec:
      type: team
      profile:
        displayName: Team B
        email: team-b@example.com
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: team-c
    spec:
      type: team
      profile:
        displayName: Team C
        email: team-c@example.com
      children: []
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-cluster-kafka
      description: DroneShop Kafka クラスター
    spec:
      type: messaging
      owner: user:default/nmushino
      system: a-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: droneshopdb-postgresql
      description: DroneShop PostgreSQL データベース
    spec:
      type: database
      owner: user:default/nmushino
      system: a-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-orders-in
      description: "Kafka トピック: orders-in"
    spec:
      type: topic
      owner: user:default/nmushino
      system: a-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-web-updates
      description: "Kafka トピック: web-updates"
    spec:
      type: topic
      owner: user:default/nmushino
      system: a-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-loyalty-updates
      description: "Kafka トピック: loyalty-updates"
    spec:
      type: topic
      owner: user:default/nmushino
      system: a-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-asite-orders-in
      description: "Kafka トピック: asite orders-in (MirrorMaker2)"
    spec:
      type: topic
      owner: user:default/nmushino
      system: b-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-bsite-orders-up
      description: "Kafka トピック: bsite orders-up (MirrorMaker2)"
    spec:
      type: topic
      owner: user:default/nmushino
      system: b-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-asite-qdca10-in
      description: "Kafka トピック: asite qdca10-in"
    spec:
      type: topic
      owner: user:default/nmushino
      system: b-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-asite-qdca10pro-in
      description: "Kafka トピック: asite qdca10pro-in"
    spec:
      type: topic
      owner: user:default/nmushino
      system: b-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-asite-inventory-in
      description: "Kafka トピック: asite inventory-in"
    spec:
      type: topic
      owner: user:default/nmushino
      system: b-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-asite-loyalty-updates
      description: "Kafka トピック: asite loyalty-updates (MirrorMaker2)"
    spec:
      type: topic
      owner: user:default/nmushino
      system: b-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-rewards
      description: "Kafka トピック: rewards"
    spec:
      type: topic
      owner: user:default/nmushino
      system: b-cluster
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Resource
    metadata:
      name: shop-bsite-rewards
      description: "Kafka トピック: bsite rewards (MirrorMaker2)"
    spec:
      type: topic
      owner: user:default/nmushino
      system: a-cluster