apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-info
  namespace: quarkusdroneshop-rhdh
data:
  catalog-info.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: User
    metadata:
      name: nmushino
      annotations:
        backstage.io/email: nmushino@redhat.com
    spec:
      profile:
        displayName: Noriaki Mushino
        email: nmushino@redhat.com
      memberOf:
        - admin

    ---
    apiVersion: backstage.io/v1alpha1
    kind: Group
    metadata:
      name: admin
    spec:
      type: root
      profile:
        displayName: Administrators
        email: nmushino@redhat.com
      children: []