apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: reward-trigger-template
  namespace: quarkusdroneshop-cicd
spec:
  params:
    - name: imageTag
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: reward-run-
      spec:
        pipelineRef:
          name: build-and-push-quarkusdroneshop-reward
        params:
          - name: IMAGE_TAG
            value: $(tt.params.imageTag)
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: quarkusdroneshop-reward-shared-workspace-pvc
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: reward-trigger-binding
  namespace: quarkusdroneshop-cicd
spec:
  params:
    - name: imageTag
      value: $(body.imageTag)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: reward-listener
  namespace: quarkusdroneshop-cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: reward-trigger-binding
      template:
        ref: reward-trigger-template