apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: backstage-template
  namespace: quarkusdroneshop-cicd
spec:
  params:
    - name: repoUrl
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: backstage-run-
      spec:
        pipelineRef:
          name: your-pipeline-name
        params:
          - name: repoUrl
            value: $(tt.params.repoUrl)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: backstage-binding
  namespace: quarkusdroneshop-cicd
spec:
  params:
    - name: repoUrl
      value: $(body.repoUrl)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: backstage-listener
  namespace: quarkusdroneshop-cicd
spec:
  serviceAccountName: pipeline
  triggers:
    - name: backstage-trigger
      bindings:
        - ref: backstage-binding
      template:
        ref: backstage-template