apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: developer-hub
  namespace: quarkusdroneshop-rhdh

spec:
  application:
    replicas: 1
    route:
      enabled: true

    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src/app-config

    extraEnvs:
      secrets:
        - name: secrets-rhdh

  database:
    enableLocalDb: true

  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - name: catalog-info
                configMap:
                  name: catalog-info

            containers:
              - name: backstage-backend
                volumeMounts:
                  - name: catalog-info
                    mountPath: /opt/app-root/catalog