kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
  namespace: quarkusdroneshop-rhdh
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  dynamic-plugins.yaml: |
    includes:
      - 'dynamic-plugins.default.yaml'
      # - package: '@redhat/backstage-plugin-tekton'
      #   disabled: false

    plugins:
      # RBAC
      - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
        disabled: false

      # GitHub Plugins
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-github-dynamic
        disabled: false

      # Kubernetes Plugins
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false

      # OpenShift Plugins
      - package: ./dynamic-plugins/dist/backstage-community-plugin-topology
        disabled: false

      # ArgoCD Plugins
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd
        disabled: false
      - package: ./dynamic-plugins/dist/roadiehq-scaffolder-backend-argocd-dynamic
        disabled: false

      # - package: ./dynamic-plugins/dist/redhat-backstage-plugin-tekton
      #   disabled: false