---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhdh-k8s-plugin
  namespace: quarkusdroneshop-rhdh
secrets:
  - name: rhdh-k8s-plugin-sa-token
---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-k8s-plugin-sa-token
  namespace: quarkusdroneshop-rhdh
  annotations:
    kubernetes.io/service-account.name: rhdh-k8s-plugin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhdh-k8s-plugin
  namespace: quarkusdroneshop-rhdh
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - resourcequotas
      - daemonsets
      - routes
      - pipelines
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-k8s-plugin-role-binding
  namespace: quarkusdroneshop-rhdh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-k8s-plugin
subjects:
- kind: ServiceAccount
  name: rhdh-k8s-plugin
  namespace: rhdh